In [38]:
import numpy as np
import pandas as pd

import scipy
from scipy import stats
from scipy.stats import pearsonr

In [10]:
df = pd.read_csv('C:/Users/zxgsh/Desktop/DS/mtcars.csv')
df.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [13]:
df['qsec'].describe()

count    32.000000
mean     17.848750
std       1.786943
min      14.500000
25%      16.892500
50%      17.710000
75%      18.900000
max      22.900000
Name: qsec, dtype: float64

In [20]:
a = np.array([[1,3], [2,4]])
b = np.array([[5,8], [7,9]])

print(a*b) # multiply element wise
print(np.dot(a, b)) # matrix multiplication

[[ 5 24]
 [14 36]]
[[26 35]
 [38 52]]


In [21]:
a = np.array([1,2,7])
b = np.array([3,8,9])

np.dot(a,b)

82

In [24]:
xx=np.array([[1.,2.,3.],[4.,5.,6.]])
yy=np.array([[10.,11.],[20.,21.],[30.,31.]])

np.dot(xx, yy)

array([[140., 146.],
       [320., 335.]])

In [26]:
a=np.array([1,8,2,6,3,8,5,5,5,5])
b=np.array([17,16,20,18,22,15,21,15,17,22])

(a+b)/10

array([1.8, 2.4, 2.2, 2.4, 2.5, 2.3, 2.6, 2. , 2.2, 2.7])

In [28]:
a=np.array([10, 15, 20])
b=([5, 7, 9])

(a-b)*7

array([35, 56, 77])

In [30]:
df = pd.read_csv('C:/Users/zxgsh/Desktop/DS/iris.csv')
df

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [40]:
pearsonr_coefficient, p_value = stats.pearsonr(df['petal.length'], df['petal.width'])
print(pearsonr_coefficient)

0.962865431402796


In [72]:
cars = pd.read_csv('C:/Users/zxgsh/Desktop/DS/mtcars.csv')

X = cars[['cyl', 'vs']]
X[(X['cyl'] == 6) & (X['vs'] == 1)]

cyl  vs
3     6   1
5     6   1
9     6   1
10    6   1

In [75]:
pd.crosstab(cars.vs, cars.cyl)

cyl   4  6   8
vs            
0     1  3  14
1    10  4   0

In [76]:
# df.idmax returns the index of maximum value in each row (for column change axis parameter value)