In [3]:
import numpy as np
from numpy.random import randn

In [4]:
np.set_printoptions(precision = 2)

In [6]:
aa = np.array([ [2.,4.,6.], [1.,3.,5.], [10.,20.,30.] ])
aa

array([[ 2.,  4.,  6.],
       [ 1.,  3.,  5.],
       [10., 20., 30.]])

In [7]:
bb = np.array([ [0.,1.,2.], [3.,4.,5.], [6.,7.,8.] ])
bb

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [8]:
aa*bb

array([[  0.,   4.,  12.],
       [  3.,  12.,  25.],
       [ 60., 140., 240.]])

In [9]:
# matrix multiplication (applied when matrices are supplied)
np.dot(aa, bb)

array([[ 48.,  60.,  72.],
       [ 39.,  48.,  57.],
       [240., 300., 360.]])

In [10]:
# dot product
a = np.array([1,2,3,4,5,6])
b = np.array([12,20,20,30,8,25])
np.dot(a, b)

422